TIME_ZONE = "Pacific Time (US & Canada)"
TWO_FACTOR_AUTHENTICATION = 'disabled'
SITE_URL = "nhri-hub.com"
SITE_NAME = "demo"
APPLICATION_ID = "https://#{SITE_URL}"
ADMIN_EMAIL = "support@#{SITE_URL}"
NO_REPLY_EMAIL = "no_reply@#{SITE_URL}"
APPLICATION_NAME = "NHRI Hub"
ORGANIZATION_NAME = "Asia Pacific Forum"
CONVENTIONS = {
    "ICERD" => "International Convention on the Elimination of All Forms of Racial Discrimination",
    "ICCPR" => "International Covenant on Civil and Political Rights",
    "ICESCR" => "International Covenant on Economic, Social and Cultural Rights",
    "CEDAW" => "Convention on the Elimination of All Forms of Discrimination against Women",
    "CAT" => "Convention against Torture and Other Cruel, Inhuman or Degrading Treatment or Punishment",
    "CRC" => "Convention on the Rights of the Child",
    "ICMW" => "International Convention on the Protection of the Rights of All Migrant Workers and Members of Their Families",
    "CPED" => "International Convention for the Protection of All Persons from Enforced Disappearance",
    "CRPD" => "Convention on the Rights of Persons with Disabilities"
    }
AGENCIES = {
    "Unassigned" => "Unassigned",
    "ACC" => "Accident Compensation Corporation",
    "CBS" => "Central Bank",
    "DBS" => "Development Bank ",
    "EPC" => "Electric Power Corporation",
    "FESA" => "Fire and Emergency Services Authority",
    "LTA" => "Land Transport Authority",
    "MAF" => "Ministry of Agriculture and Fisheries",
    "MCIL" => "Ministry of Commerce Industry and Labour",
    "MCIT" => "Ministry of Communications and Information Technology",
    "MESC" => "Ministry of Education, Sports and Culture",
    "MFAT" => "Ministry of Foreign Affairs and Trade",
    "MJCA" => "Ministry of Justice and Courts Administration",
    "MNRE" => "Ministry of Natural Resources and Environment",
    "MOP" => "Minister of Police",
    "MOPPS" => "Ministry of Police and Prisons",
    "MOR" => "Ministry of Revenue",
    "MPE" => "Ministry of Public Enterprises",
    "MPMC" => "Ministry of the Prime Minister and Cabinet",
    "MWCSD" => "Ministry of Women, Community and Social Development",
    "MWTI" => "Ministry of Works, Transport and Infrastructure",
    "MoF" => "Ministry of Finance",
    "MoFA" => "Ministry of Foreign Affairs",
    "MoH" => "Ministry of Health",
    "NHS" => "National Health Service",
    "NUS" => "National University ",
    "PSC" => "Public Services Commission",
    "PTO" => "Public Trust Office",
    "SAA" => "Airport Authority",
    "SAO" => "Audit Office",
    "SBS" => "Bureau of Statistics",
    "SFESA" => "Fire and Emergency Services Authority",
    "SHC" => "Housing Corporateion",
    "SIFA" => "International Finance Authority",
    "SLAC" => "Life Assurance Corporation",
    "SLC" => "Land Corporation",
    "SLRC" => "Law Reform Commission",
    "SNKF" => "National Kidney Foundation",
    "SNPF" => "National Provident Fund",
    "SPA" => "Ports Authority",
    "SQA" => "Qualifications Authority",
    "SROS" => "Scientific Research Organization ",
    "SSC" => "Shipping Corporation",
    "SSFA" => "Sports and Facilities Authority",
    "SSS" => "Shipping Services",
    "STA" => "Tourism Authority",
    "STEC" => "Trust Estates Corporation",
    "SWA" => "Water Authority",
    "UTS" => "Unit Trust "
       }
AWS_ACCOUNT_ID = "918359762546"

STAFF = [ { group: nil,
            office: "OFFICE OF THE CHIEF OPERATING OFFICER",
            title: "COO",
            prefix: nil,
            name: nil },
          { group: "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Administrative Justice and Service Delivery (AJSD)",
            title: "Executive Manager",
            prefix:  "Ms",
            name:  "P Mogaladi"},
          { group: "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Administrative Justice and Service Delivery (AJSD)",
            title: "Chief Investigator: Unit 1",
            prefix:  "Mr",
            name:  "S Mothupi" },
          { group: "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Administrative Justice and Service Delivery (AJSD)",
            title: "Chief Investigator: Unit 2",
            prefix:  "Adv",
            name:  "J Raubenheimer" },
          { group:  "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Good Governance and Integrity (GGI)",
            title:  "Executive Manager",
            prefix: "Ms",
            name:   "P Mogaladi"},
          { group:  "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Good Governance and Integrity (GGI)",
            title:  "Chief Investigator: Unit 1",
            prefix: "Mr",
            name:   "A Madiba"},
          { group:  "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Complaints and Stakeholder Management (CSM)",
            title:  "Executive Manager",
            prefix: "Ms",
            name:   "F Motsitsi"},
          { group:  "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Complaints and Stakeholder Management (CSM)",
            title:  "Chief Investigator",
            prefix: "Mr",
            name:   "R Mataboge"},
          { group:  "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Complaints and Stakeholder Management (CSM)",
            title:  "Senior Manager: Complaints & Stakeholder Management (Intake and assessment)",
            prefix: "Mr",
            name:   "B Neshunzhi"},
          { group:  "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Complaints and Stakeholder Management (CSM)",
            title:  "Senior Manager: Complaints & Stakeholder Management",
            prefix: "Ms",
            name:   "K Masibi"},
          { group:  "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Provincial Investigation and Integration (inland) (PII1)",
            title:  "Executive Manager",
            prefix: "Ms",
            name:   "N Thejane"},
          { group:  "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Provincial Investigation and Integration (inland) (PII1)",
            title:  "Chief Investigator",
            prefix: "Adv",
            name:   "E De Waal"},
          { group:  "HEAD OFFICE INVESTIGATION BRANCHES",
            office: "Provincial Investigation and Integration (Coastal) (PII2 )",
            title:  "Executive Manager",
            prefix: "Adv",
            name:   "S Fourie"},
          { group:  "PROVINCIAL OFFICES",
            office: "Gauteng",
            title:  "Provincial Representative",
            prefix: "Ms",
            name:   "Winnie Manyathela"},
          { group:  "PROVINCIAL OFFICES",
            office: "Mpumalanga",
            title:  "Provincial Representative",
            prefix: "Mr",
            name:   "Botromia Sithole"},
          { group:  "PROVINCIAL OFFICES",
            office: "North West",
            title:  "Provincial Representative",
            prefix: "Mr",
            name:   "Sechele Keebine"},
          { group:  "PROVINCIAL OFFICES",
            office: "Western Cape",
            title:  "Provincial Representative:",
            prefix: "Ms",
            name:   "Sune Griessel"},
          { group:  "PROVINCIAL OFFICES",
            office: "KwaZulu-Natal",
            title:  "Provincial Representative:",
            prefix: "Adv",
            name:   "Mlandeli Nkosi"},
          { group:  "PROVINCIAL OFFICES",
            office: "Limpopo",
            title:  "Provincial Representative",
            prefix: "Mr",
            name:   "George Matimolane"},
          { group:  "PROVINCIAL OFFICES",
            office: "Free State",
            title:  "Provincial Representative",
            prefix: "Mr",
            name:   "Sphelo Samuel"},
          { group:  "PROVINCIAL OFFICES",
            office: "Northern Cape",
            title:  "Provincial Representative",
            prefix: "Mr",
            name:   "Mlungisi Khanya"},
          { group:  "PROVINCIAL OFFICES",
            office: "Eastern Cape",
            title:  "Provincial Representative/ Executive Manager",
            prefix: "Adv",
            name:   "S Fourie"},
          { group:  "REGIONAL OFFICES",
            office: "George",
            title:  "Regional Manager",
            prefix: "Adv",
            name:   "G Landman"},
          { group:  "REGIONAL OFFICES",
            office: "Kuruman",
            title:  "Regional Manager",
            prefix: "Ms",
            name:   "Tshiamo Segomoco"},
          { group:  "REGIONAL OFFICES",
            office: "Klerksdorp",
            title:  "Regional Manager",
            prefix: "Mr",
            name:   "Ditlhake Motona"},
          { group:  "REGIONAL OFFICES",
            office: "Mthatha",
            title:  "Regional Manager",
            prefix:  nil,
            name:   "Mthwakazi Thomas"},
          { group:  "REGIONAL OFFICES",
            office: "Musina",
            title:  "Regional Manager",
            prefix: "Mr",
            name:   "Makgale Levy Hiine"},
          { group:  "REGIONAL OFFICES",
            office: "Pietermaritzburg",
            title:  "Regional Manager",
            prefix:  nil,
            name: nil},
          { group:  "REGIONAL OFFICES",
            office: "Rustenburg",
            title:  "Regional Manager",
            prefix:  nil,
            name:   "Kleinbooi Matsetela"},
          { group:  "REGIONAL OFFICES",
            office: "Upington",
            title:  "Regional Manager",
            prefix:  nil,
            name:   "Ephraim Minnaar"},
          { group:  "REGIONAL OFFICES",
            office: "Phuthaditjhaba",
            title:  "Regional Manager",
            prefix:  nil,
            name:   "Qabang Mofokeng"}
          ]

CaseReferenceFormat="7/2-%05<sequence>i/%<year>i"

LEGISLATIONS = [ {short_name: "PPA", full_name: "Public Protector Act"},
                 {short_name: "EMEA", full_name: "Executive Members Ethics Act"},
                 {short_name: "PAIA", full_name: "Promotion of Access to Information Act"},
                 {short_name: "PDA", full_name: "Protected Disclosures Act"},
                 {short_name: "PCCAA", full_name: "Prevention and Combating of Corrupt Activities Act"},
                 {short_name: "PFMA", full_name: "Public Finance Management Act"},
                 {short_name: "PEPUDA", full_name: "Promotion of Equality and Prevention of Unfair Discrimination Act"},
                 {short_name: "NARSSA", full_name: "Electoral Commission Act, National Archives and Records Service Act"},
                 {short_name: "NERA", full_name: "National Energy Regulatory Act"},
                 {short_name: "LA", full_name: "Lotteries Act"},
                 {short_name: "SIUSTA", full_name: "Special Investigating Units and Special Tribunals Act"},
                 {short_name: "NEMA", full_name: "National Environmental Management Act"},
                 {short_name: "", full_name: "The Constitution"} ]

NationalGovernmentAgencies = ["Department of Agriculture, Forestry and Fisheries",
                              "Department of Arts and Culture ",
                              "Department of Basic Education",
                              "Civilian Secretariat for Police",
                              "Department of Communications",
                              "Department of Cooperative Governance and Traditional Affairs",
                              "Department of Correctional Services",
                              "Department of Defence",
                              "Department of Economic Development",
                              "Department of Energy ",
                              "Department of Environmental Affairs ",
                              "Department of Health",
                              "Department of Higher Education and Training",
                              "Department of Home Affairs",
                              "Department of Human Settlements",
                              "Independent Police Investigative Directorate",
                              "Department of International Relations and Cooperation",
                              "Department of Justice and Constitutional Development",
                              "Department of Labour",
                              "Department of Military Veterans",
                              "Department of Mineral Resources ",
                              "National Treasury",
                              "Department of Performance Monitoring and Evaluation",
                              "Public Administration Leadership and Management Academy",
                              "Department of Public Enterprises",
                              "Department of Public Service and Administration",
                              "Public Service Commission",
                              "Department of Public Works",
                              "Department of Rural Development and Land Reform",
                              "Department of Science and Technology",
                              "Department of Social Development ",
                              "South African Police Service",
                              "South African Revenue Service",
                              "State Security Agency",
                              "Department of Sport and Recreation South Africa",
                              "Statistics South Africa",
                              "Department of Tourism ",
                              "Department of Trade and Industry",
                              "Department of Traditional Affairs",
                              "Department of Transport",
                              "Department of Water Affairs",
                              "Department of Women, Children & People with Disabilities",
                              "The Presidency"]

NationalGovernmentInstitutions = ["Independent Complaints Directorate",
                                  "National Intelligence Agency",
                                  "National Treasury",
                                  "Public Service Commission",
                                  "Public Administration Leadership and Management Academy ",
                                  "South African Police Service",
                                  "South African Revenue Service",
                                  "South African Secret Service",
                                  "Statistics South Africa"]

DemocracySupportingStateInstitutions = ["The Auditor-General",
                                        "The Commission for the Promotion and Protection of the Rights of Cultural, Religious and Linguistic Communities",
                                        "The Commission on Gender Equality",
                                        "The Human Rights Commission",
                                        "The Independent Electoral Commission",
                                        "The Public Protector"]

Provinces = ["Gauteng", "Mpumalanga", "North West", "Western Cape", "Limpopo", "Free State", "Northern Cape", "Eastern Cape", "KwaZulu-Natal"]
